### ISSUE TITLE
error adding symbols: file in wrong format

### ISSUE THREAD

**Issue by TawsTm** [Granjow/fmod-service#1]
After installing all dependencies i tried making the build and got an error while doing so:

    [  5%] Linking CXX executable unitTest
    /usr/bin/ld: 
    ../lib/fmodstudioapi20203linux/api/core/lib/x86_64/libfmodL.so: error adding symbols: file in wrong format
    collect2: error: ld returned 1 exit status
    make[2]: *** [CMakeFiles/unitTest.dir/build.make:225: unitTest] Error 1
    make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/unitTest.dir/all] Error 2
    make: *** [Makefile:103: all] Error 2

I am running Raspberry Pi OS with **64-Bit** architecture on a **Raspberry Pi 3 Model B Rev 1.2**

I can't figure out the problem, but after some research i think it might be a problem with the architecture, since this is not an unknown error in other projects aswell. 

Maybe i'm just doing something wrong since i'm no expert in CMake, but some help would be gladly appreciated.

**Comment by Granjow** [comment]
Hi @TawsTm , are you using `cmake -DCPU=arm …`?

**Comment by TawsTm** [comment]
Thanks for your reply @Granjow!

I tried but this didn't work for me. I added a new possible CPU `arm64` with `-march=armv8` so that the arm64 folder of the fmodstudioapi path would be used and it at least didn't crash with `cmake -DCPU=arm64`.

I'm not sure about the outcome though. The progress percentage did show 5% till the end but a fmod-service target is created. One warning occured but no error:

```
.../fmod-service/src/ZmqApi.cpp:110:49: warning: ignoring return value of 
‘zmq::recv_result_t zmq::detail::socket_base::recv(zmq::message_t&, zmq::recv_flags)’, declared with attribute
‘nodiscard’ [-Wunused-result]
  110 |         sock.recv(message, zmq::recv_flags::none);
      |                                                 ^
In file included from .../fmod-service/src/ZmqApi.cpp:3:
.../fmod-service/src/../lib/cppzmq/zmq.hpp:2010:19: note: declared here
 2010 |     recv_result_t recv(message_t &msg, recv_flags flags = recv_flags::none)
      |                   ^~~~
```

Is this expected or should i worry?
I will need to figure out how to use it before i can tell you more about the functionality 👍 .

**Comment by Granjow** [comment]
Hi @TawsTm ,

that looks good, you can ignore the warning, that does not affect functionality.
You can use it together with https://www.npmjs.com/package/@geheimgang188/fmod-service-api if you use Node.js, check https://github.com/Granjow/fmod-service-api/blob/master/src/demo/demo-player.ts which you can run on the sample project that is shipped with FMOD Studio.

**Comment by TawsTm** [comment]
I am able to run the demo, thank you!
I will mark this Issue as solved but will be asking some questions in another issue :D
